### ISSUE TITLE
bug反馈与新想法的提出

### ISSUE THREAD

**Issue by hibetterheyj** [cubesky/hexo-helper-post-top#2]
**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

开发者，您好！我在使用Material的过程中使用了该插件~

- 出现了一个**bug**，即当在生成模板`post.md`中的`front-matter`部分设置`top: `无论后面填入`true`或者`false`都会出现[TOP]置顶效果，所以目前方法是，仅对需要的文章添加`top: true`字段。

- 希望增加**新的功能**——希望在不同的catagory都有特殊的置顶功能。

十分感谢！

**Comment by NanerLee** [comment]
我也遇到了这个bug, 不知道是主题的问题还是插件的问题

**Comment by cubesky** [comment]
这确实是这个插件的问题， 忽略了 top 的值，我将在2天内修复。 对于不同 catagory 的功能需要主题配合。

**Comment by cubesky** [comment]
已更新

**Comment by hibetterheyj** [comment]
十分感谢~
